import { MeetingInsight } from '@prisma/client';

// Defines the structure for insights generated by processors before saving.
// Omits fields that are automatically handled by Prisma (id, createdAt, updatedAt).
// We ensure meetingId is present before saving.
export type InsightData = Omit<MeetingInsight, 'id' | 'createdAt' | 'updatedAt' | 'relevanceScore' | 'metadata'> & {
    meetingId: number;
    // Make content optional initially if not always present? For now, assume it's required.
};

// You can add other shared types here later if needed. 